[options]
db_host = False
db_port = False
db_user = jochen
db_password = False
default_productivity_apps = True
dbfilter = ^ryadev$
list_db = True
;;;longpolling_port = 8072
; Option für WebSocket / Evented Server
;;;gevent = True
; Longpolling server (requires workers > 0)
;workers = 2
max_cron_threads = 1
;;;proxy_mode = True
admin_passwd = $pbkdf2-sha512$600000$dc6515oz5tyb03ovBSAEgA$Ds/NbkU0MIKI2gO.p8qUGtqnwNwgaDP1iSBwBnTJf7pAq3g1FO7Fcbye2YGBucSvukHsncfWm18ZS1Na98ZN0Q
;;;addons_path = /home/jochen/git/odoo/addons

log_level = debug
log_handler = :DEBUG,watchdog.observers.inotify_buffer:INFO
dev_mode = all
reload = True
workers = 0